version: '3.1'

volumes:
  postgres:
  assets:

services:
  db:
    image: postgres:9.6
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: univ_app_development
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]

  server_app: &server_app
    build: .
    command: bundle exec rails server
    entrypoint: "./docker-entrypoint.sh"
    volumes:
      - ./app:/home/www/univ_app/app
      - ./config:/home/www/univ_app/config
      - ./public:/home/www/univ_app/public
      - ./tmp:/home/www/univ_app/tmp
      - ./log:/home/www/univ_app/log
      - assets:/home/www/univ_app/public/assets
    tty: true
    stdin_open: true
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: univ_app_development
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
